name: "pre-commit autoupdate"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pre-commit-autoupdate:
    uses: darbiadev/.github/.github/workflows/generic-precommit-autoupdate.yaml@a191041c5139218df2feb95690ac747c41113052
