name: "Python CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@a191041c5139218df2feb95690ac747c41113052

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@a191041c5139218df2feb95690ac747c41113052

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@a191041c5139218df2feb95690ac747c41113052
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
